# -*- coding: utf-8 -*-
"""Project 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dw-EXdzZ-AI--JUI0_nI_Bpj8CHwDufy

# Import Libraries and Data
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import datetime
from matplotlib import pyplot as plt
import cufflinks as cf
import warnings
warnings.filterwarnings("ignore")

#!pip install pmdarima --quiet
import pmdarima as pm

#!pip install tvdatafeed --quiet
from tvDatafeed import TvDatafeed ,Interval

# %matplotlib inline

tv = TvDatafeed()
data = tv.get_hist(symbol='TCS',exchange='NSE',n_bars=5000)
data['date'] = data.index.astype(str)
new = data['date'].str.split(' ',expand=True)
data['date'] = new[0]
data['date'] = pd.to_datetime(data['date'])
data = data.set_index('date')
data


"""#FB PROPHET"""

#!pip install pystan~=2.14 --quiet
#!pip install fbprophet --quiet

import fbprophet
from fbprophet import Prophet

data2 = data
data2['ds'] = pd.to_datetime(data['date'])
data2['y'] = (data2['close'])
data2 = data2[['ds','y']].reset_index(drop = True)
data2.info()

data2

model = Prophet()
model.fit(data2)
model

future = model.make_future_dataframe(periods = 730)
future

pred = model.predict(future)
pred

pred[['ds','yhat','yhat_lower','yhat_upper']].head()

model.plot(pred)

model.plot_components(pred)

se = np.square(pred.loc[:, 'yhat'] - data2.y)
mse = np.mean(se)
rmse = np.sqrt(mse)
rmse


